# Generated by Django 2.1.7 on 2019-06-06 02:42

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('track_name', models.CharField(max_length=128, null=True)),
                ('device_id', models.CharField(max_length=128)),
                ('pm25', models.DecimalField(decimal_places=6, max_digits=19)),
                ('pm10', models.DecimalField(decimal_places=6, max_digits=19, null=True)),
                ('humidity', models.DecimalField(decimal_places=6, max_digits=19, null=True)),
                ('spd', models.DecimalField(decimal_places=6, max_digits=19, null=True)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=19, null=True)),
                ('sampled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
