version: '3'

services:

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  timescaledb:
    image: timescale/timescaledb-postgis
    ports:
      - "15432:5432"
    build:
      context: .
      args:
        - db_name=canairio
      dockerfile: Dockerfile_timescaledb
    environment:
      - POSTGRES_USER=canairio
      - POSTGRES_PASSWORD=canairio
      - POSTGRES_DB=canairio
      - POSTGRES_TEST_DB=canairio_test
  web:
    build: .
    command: ./start
    volumes:
      - .:/canairio
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - timescaledb
    links:
      - influxdb
      - timescaledb
    environment:
      - DJANGO_SETTINGS_MODULE=canairio.settings.development
      - DATABASE_USERNAME=canairio
      - DATABASE_PASSWORD=canairio
      - POSTGRESQL_HOST=timescaledb
      - INFLUXDB_HOST=influxdb
