version: '3'

services:

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  timescaledb:
    image: timescale/timescaledb-postgis
    ports:
      - "15432:5432"

  web:
    build: .
    command: ./start
    volumes:
      - .:/canairio
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - timescaledb
    links:
      - influxdb
      - timescaledb
    environment:
      - INFLUXDB_HOST=influxdb
      - POSTGRESQL_HOST=timescaledb
