version: '3'

services:

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  web:
    build: .
    command: ./start
    volumes:
      - .:/canairio
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb

