version: '3'

services:

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/canairio
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    links:
      - influxdb
