version: 2
jobs:
  build:
    working_directory: ~/circleci-canairio
    environment:
      CIRCLE_ENV: true
      DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      INFLUXDB_HOST: localhost
      DJANGO_SETTINGS_MODULE: canairio.settings.development
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: canairio
      POSTGRESQL_HOST: localhost
      INFLUXDB_DATABASE: canairio
      DATABASE_NAME: circle_test
      ENVIRONMENT: development
    docker:
      - image: circleci/python:3.6.4-stretch
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: influxdb
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: sudo apt-get install -y libpq-dev libxml2-dev libxmlsec1-dev libxmlsec1-openssl influxdb-client binutils libproj-dev gdal-bin
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Lint code after importing dependencies
          command: |
            scripts/pylint.sh
#      - run:
#          name: Create an influxdb
#          command: |
#            scripts/create_influx_db.sh
      - run:
          command: |
            python manage.py test --settings=canairio.settings.testing
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
